// <auto-generated />
using System;
using GAC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GAC.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260621103724_AddSpecPdfAndDock")]
    partial class AddSpecPdfAndDock
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GAC.Core.Content.ColorOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("ColorOptions");
                });

            modelBuilder.Entity("GAC.Core.Content.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("GAC.Core.Content.ContentSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContentPageId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentPageId");

                    b.ToTable("ContentSections");
                });

            modelBuilder.Entity("GAC.Core.Content.DockItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("DockItems");
                });

            modelBuilder.Entity("GAC.Core.Content.FeatureSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("FeatureSections");
                });

            modelBuilder.Entity("GAC.Core.Content.FormPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("FormPages");
                });

            modelBuilder.Entity("GAC.Core.Content.HeroSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CtaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomePageId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomePageId");

                    b.ToTable("HeroSlides");
                });

            modelBuilder.Entity("GAC.Core.Content.HomePage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("HomePages");
                });

            modelBuilder.Entity("GAC.Core.Content.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormType")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("PreferredDate")
                        .HasColumnType("date");

                    b.Property<string>("SourcePage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("GAC.Core.Content.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("GAC.Core.Content.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("GAC.Core.Content.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PublishedOn")
                        .HasColumnType("date");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("GAC.Core.Content.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("GAC.Core.Content.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapchatUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiktokUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("GAC.Core.Content.SpecGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("SpecGroups");
                });

            modelBuilder.Entity("GAC.Core.Content.SpecRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("SpecGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecGroupId");

                    b.ToTable("SpecRows");
                });

            modelBuilder.Entity("GAC.Core.Content.Trim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SpecPdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trims");
                });

            modelBuilder.Entity("GAC.Core.Content.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrochurePdf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PriceFrom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SpecPdf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GAC.Core.Content.VehicleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleImages");
                });

            modelBuilder.Entity("GAC.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GAC.Core.Content.ColorOption", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", null)
                        .WithMany("Colors")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("ColorOptionId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ColorOptionId");

                            b1.ToTable("ColorOptions");

                            b1.WithOwner()
                                .HasForeignKey("ColorOptionId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.ContentPage", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "BodyHtml", b1 =>
                        {
                            b1.Property<int>("ContentPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentPageId");

                            b1.ToTable("ContentPages");

                            b1.WithOwner()
                                .HasForeignKey("ContentPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaDescription", b1 =>
                        {
                            b1.Property<int>("ContentPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentPageId");

                            b1.ToTable("ContentPages");

                            b1.WithOwner()
                                .HasForeignKey("ContentPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaTitle", b1 =>
                        {
                            b1.Property<int>("ContentPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentPageId");

                            b1.ToTable("ContentPages");

                            b1.WithOwner()
                                .HasForeignKey("ContentPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("ContentPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentPageId");

                            b1.ToTable("ContentPages");

                            b1.WithOwner()
                                .HasForeignKey("ContentPageId");
                        });

                    b.Navigation("BodyHtml")
                        .IsRequired();

                    b.Navigation("MetaDescription")
                        .IsRequired();

                    b.Navigation("MetaTitle")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.ContentSection", b =>
                {
                    b.HasOne("GAC.Core.Content.ContentPage", null)
                        .WithMany("Sections")
                        .HasForeignKey("ContentPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("ContentSectionId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentSectionId");

                            b1.ToTable("ContentSections");

                            b1.WithOwner()
                                .HasForeignKey("ContentSectionId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Heading", b1 =>
                        {
                            b1.Property<int>("ContentSectionId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ContentSectionId");

                            b1.ToTable("ContentSections");

                            b1.WithOwner()
                                .HasForeignKey("ContentSectionId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Heading")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.DockItem", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("DockItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DockItemId");

                            b1.ToTable("DockItems");

                            b1.WithOwner()
                                .HasForeignKey("DockItemId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "ShortLabel", b1 =>
                        {
                            b1.Property<int>("DockItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("DockItemId");

                            b1.ToTable("DockItems");

                            b1.WithOwner()
                                .HasForeignKey("DockItemId");
                        });

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("ShortLabel")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.FeatureSection", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", null)
                        .WithMany("Features")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("FeatureSectionId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FeatureSectionId");

                            b1.ToTable("FeatureSections");

                            b1.WithOwner()
                                .HasForeignKey("FeatureSectionId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Heading", b1 =>
                        {
                            b1.Property<int>("FeatureSectionId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FeatureSectionId");

                            b1.ToTable("FeatureSections");

                            b1.WithOwner()
                                .HasForeignKey("FeatureSectionId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Heading")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.FormPage", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "BodyHtml", b1 =>
                        {
                            b1.Property<int>("FormPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FormPageId");

                            b1.ToTable("FormPages");

                            b1.WithOwner()
                                .HasForeignKey("FormPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "IntroText", b1 =>
                        {
                            b1.Property<int>("FormPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FormPageId");

                            b1.ToTable("FormPages");

                            b1.WithOwner()
                                .HasForeignKey("FormPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaDescription", b1 =>
                        {
                            b1.Property<int>("FormPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FormPageId");

                            b1.ToTable("FormPages");

                            b1.WithOwner()
                                .HasForeignKey("FormPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaTitle", b1 =>
                        {
                            b1.Property<int>("FormPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FormPageId");

                            b1.ToTable("FormPages");

                            b1.WithOwner()
                                .HasForeignKey("FormPageId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("FormPageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FormPageId");

                            b1.ToTable("FormPages");

                            b1.WithOwner()
                                .HasForeignKey("FormPageId");
                        });

                    b.Navigation("BodyHtml")
                        .IsRequired();

                    b.Navigation("IntroText")
                        .IsRequired();

                    b.Navigation("MetaDescription")
                        .IsRequired();

                    b.Navigation("MetaTitle")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.HeroSlide", b =>
                {
                    b.HasOne("GAC.Core.Content.HomePage", null)
                        .WithMany("Slides")
                        .HasForeignKey("HomePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "CtaText", b1 =>
                        {
                            b1.Property<int>("HeroSlideId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HeroSlideId");

                            b1.ToTable("HeroSlides");

                            b1.WithOwner()
                                .HasForeignKey("HeroSlideId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Heading", b1 =>
                        {
                            b1.Property<int>("HeroSlideId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HeroSlideId");

                            b1.ToTable("HeroSlides");

                            b1.WithOwner()
                                .HasForeignKey("HeroSlideId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Subheading", b1 =>
                        {
                            b1.Property<int>("HeroSlideId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("HeroSlideId");

                            b1.ToTable("HeroSlides");

                            b1.WithOwner()
                                .HasForeignKey("HeroSlideId");
                        });

                    b.Navigation("CtaText")
                        .IsRequired();

                    b.Navigation("Heading")
                        .IsRequired();

                    b.Navigation("Subheading")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.Lead", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GAC.Core.Content.MediaAsset", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Alt", b1 =>
                        {
                            b1.Property<int>("MediaAssetId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("MediaAssets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("Alt")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.MenuItem", b =>
                {
                    b.HasOne("GAC.Core.Content.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("MenuItemId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MenuItemId");

                            b1.ToTable("MenuItems");

                            b1.WithOwner()
                                .HasForeignKey("MenuItemId");
                        });

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GAC.Core.Content.NewsArticle", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("NewsArticleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Excerpt", b1 =>
                        {
                            b1.Property<int>("NewsArticleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("NewsArticleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NewsArticleId");

                            b1.ToTable("NewsArticles");

                            b1.WithOwner()
                                .HasForeignKey("NewsArticleId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Excerpt")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.Offer", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Body", b1 =>
                        {
                            b1.Property<int>("OfferId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("OfferId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("Body")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.SiteSettings", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "FooterTagline", b1 =>
                        {
                            b1.Property<int>("SiteSettingsId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SiteSettingsId");

                            b1.ToTable("SiteSettings");

                            b1.WithOwner()
                                .HasForeignKey("SiteSettingsId");
                        });

                    b.Navigation("FooterTagline")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.SpecGroup", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", null)
                        .WithMany("SpecGroups")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Title", b1 =>
                        {
                            b1.Property<int>("SpecGroupId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SpecGroupId");

                            b1.ToTable("SpecGroups");

                            b1.WithOwner()
                                .HasForeignKey("SpecGroupId");
                        });

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.SpecRow", b =>
                {
                    b.HasOne("GAC.Core.Content.SpecGroup", null)
                        .WithMany("Rows")
                        .HasForeignKey("SpecGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("SpecRowId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SpecRowId");

                            b1.ToTable("SpecRows");

                            b1.WithOwner()
                                .HasForeignKey("SpecRowId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Value", b1 =>
                        {
                            b1.Property<int>("SpecRowId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("SpecRowId");

                            b1.ToTable("SpecRows");

                            b1.WithOwner()
                                .HasForeignKey("SpecRowId");
                        });

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.Trim", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", null)
                        .WithMany("Trims")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Highlights", b1 =>
                        {
                            b1.Property<int>("TrimId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TrimId");

                            b1.ToTable("Trims");

                            b1.WithOwner()
                                .HasForeignKey("TrimId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("TrimId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TrimId");

                            b1.ToTable("Trims");

                            b1.WithOwner()
                                .HasForeignKey("TrimId");
                        });

                    b.Navigation("Highlights")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.Vehicle", b =>
                {
                    b.OwnsOne("GAC.Core.Content.LocalizedText", "BodyHtml", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "IntroText", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaDescription", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "MetaTitle", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Tagline", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");
                        });

                    b.Navigation("BodyHtml")
                        .IsRequired();

                    b.Navigation("IntroText")
                        .IsRequired();

                    b.Navigation("MetaDescription")
                        .IsRequired();

                    b.Navigation("MetaTitle")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Tagline")
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.VehicleImage", b =>
                {
                    b.HasOne("GAC.Core.Content.Vehicle", null)
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GAC.Core.Content.LocalizedText", "Alt", b1 =>
                        {
                            b1.Property<int>("VehicleImageId")
                                .HasColumnType("int");

                            b1.Property<string>("Ar")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("En")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("VehicleImageId");

                            b1.ToTable("VehicleImages");

                            b1.WithOwner()
                                .HasForeignKey("VehicleImageId");
                        });

                    b.Navigation("Alt")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GAC.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GAC.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GAC.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GAC.Core.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GAC.Core.Content.ContentPage", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("GAC.Core.Content.HomePage", b =>
                {
                    b.Navigation("Slides");
                });

            modelBuilder.Entity("GAC.Core.Content.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("GAC.Core.Content.SpecGroup", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("GAC.Core.Content.Vehicle", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Features");

                    b.Navigation("Images");

                    b.Navigation("SpecGroups");

                    b.Navigation("Trims");
                });
#pragma warning restore 612, 618
        }
    }
}
